services:
  - type: web
    name: digital-menu-backend
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: digital-menu-db
          property: connectionString

databases:
  - name: digital-menu-db
    plan: free
